on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel a lot of binaries
        # https://golang.org/doc/install/source#environment See supported Go OS/Arch pairs here
        goos: [ linux, darwin, openbsd, netbsd, dragonfly, plan9, windows, solaris, illumos ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: dragonfly
          - goarch: arm64
            goos: plan9
          - goarch: arm64
            goos: illumos
          - goarch: arm64
            goos: solaris
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          project_path: ./cmd/healthcheck
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "sui-probe"
          extra_files: LICENSE README.md
          ldflags: "-s -w"
